### ISSUE TITLE
Add custom template for controls button

### ISSUE THREAD

**Issue by AndreySukhov** [kidjp85/react-id-swiper#100]
Originally, Swiper provides flexible controls structure, html example
```<div class="swiper-button-prev"><span class="font-icon-big-arr-left"></span></div>```

It would be great feature to  pass some jsx to slider params for this case.

Thank you for this plugin and your attention.

**Comment by kidjp85** [comment]
I'm thinking of that idea too. Try to make it in next release.

**Comment by gareys** [comment]
You can create a custom navigation and do this yourself for the time being. I personally prefer this way of implementing navigation.

```
nextSlide() {
  if (this.swiper) {
    this.swiper.slideNext();
  }
}

prevSlide() {
  if (this.swiper) {
    this.swiper.slidePrev();
  }
}

render() {
    return (
      <div>
        <Swiper {...settings} ref={node => this.swiper = node !== null ? node.swiper : null }>
          {slides}
        </Swiper>
        <div className="swiper-button-next" onClick={this.nextSlide} />
        <div className="swiper-button-prev" onClick={this.prevSlide} />
      </div>
    );
}
```

You'll need to implement a little more logic in order to append a disabled state once you've reached the end of the swiper.

I have had trouble rendering JSX to a string for swiper to digest, so the above example allows for full customization of the swiper navigation. Unfortunately, swiper only accepts a string or html element as values for `nextEl` and `prevEl` in the `navigation` settings. I would suggest that you build a custom navigation since JSX cannot be rendered to an html string unless you use ReactDOM server.
