### ISSUE TITLE
swiper.appendSlide, swiper.prependSlide with React Components

### ISSUE THREAD

**Issue by kryl** [kidjp85/react-id-swiper#127]
Hi!
How can i append, prepend slides like this
```
swiper.append(<MyComponent {..props} />)
```
or like this
```
<div class="swiper-slide"><MyComponent {..props} /></div>
```
Now  i see, that i can use this opts only with DOM Node like
```
'<div class="swiper-slide">Slide</div>'
```
Otherwise i get an error
```
TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
```

**Comment by kidjp85** [comment]
Hi @kryl 

For now, I don't think we support prepend or append slide.

**Comment by floifyrandy** [comment]
@kidjp85 Curious if this is this is being planned? I'm on a project that's fairly dynamic and needs to rely on appedSlide quite a bit. Looking around, I see the function at least [exists](https://github.com/kidjp85/react-id-swiper/blob/master/lib/react-id-swiper.js#L3142).

Also, did you leave it out for a specific reason? Eg: impossible to implement? I'm only asking because I'm going to see if I can get the feature in myself, but if you've already determined it's not possible, I'll have to move to something else.

**Comment by LennyLip** [comment]
Hi @kidjp85  How can I add a new page of slides and save existing navigation position? rebuildOnUpdate: true, drop me to the first slide.

```
<Swiper {...this.params} >
             {this.state.Slides}
</Swiper>
```

**Comment by danedavid** [comment]
@LennyLip Set `shouldSwiperUpdate={true}`. Worked for me.

**Comment by LennyLip** [comment]
Thanks,  @danedavid I tried shouldSwiperUpdate, but the slider did not update after new slides added to exists slides list. With rebuildOnUpdate new slides appearing, but navigation moved to the first slide.

Can you please give me your code with a working example.
