### ISSUE TITLE
Coverflow effect problem in FireFox

### ISSUE THREAD

**Issue by EttoreS** [kidjp85/react-id-swiper#145]
I already searched in the issues (here and in the issues of the swiper plugin) but couldn’t find anything related. If there already exists one, please forgive me and point me to the right spot. If you think this is a problem with the swiper lib, I will open the issue there.

I use the Coverflow effect, with a structure like this:

```
<Swiper {...params}>
    {this.props.albumSlides.map((item, index) =>{
         return (
             <div key={index} >
                 <button href={item.get('link')}></button>
             </div>
         )
    })}
</Swiper>
```

Unfortunately the button is not clickable, because the div “swiper-wrapper” intercepts the click events. This happens ONLY in firefox.

These are our Swiper params:

```
const params = {
    effect: 'coverflow',
    loop: false,
    centeredSlides: true,
    slidesPerView: 4,
    initialSlide: 3,
    keyboardControl: true,
    mousewheelControl: true,
    lazyLoading: false,
    slideActiveClass: 'swiper-slide-active',
    preventClicks: true,
    preventClicksPropagation: true,
    slideToClickedSlide: true,
    grabCursor: true,
    lazyLoadingInPrevNext: true,
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev'
    },
    coverflowEffect: {
        rotate: 0,
        stretch: -25,
        depth: 100,
        modifier: 5,
        slideShadows : false,
    },
    breakpoints: {
        // when window width is <= 320px
        320: {
            slidesPerView: 1,
            spaceBetween: 10
        },
        // when window width is <= 480px
        480: {
            slidesPerView: 2,
            spaceBetween: 20
        },
        // when window width is <= 640px
        640: {
            slidesPerView: 2,
            spaceBetween: 20
        },
        1920:{
            slidesPerView: 4,
            spaceBetween: 20
        }
    }
};
```

**Comment by polvora-fosforo** [comment]
Hello @kidjp85 sorry for the late response, too. Ettore is not more working with us so we did not get notified about your reply, unfortunately. I am now taking care of this task and here is the codepen showing the problem: https://codepen.io/polvora_fosforo/pen/zYYELGw

Note, this problem only happens on firefox (tested on chrome, safari, internet explorer, edge and opera, and it works as it should).

This pen i created uses Swiper version 4.0.6 because i wasn't able get any cdn avaliable at https://kidjp85.github.io/doc/get-started/ to work.

Also, please note that I used the same example from https://codepen.io/anon/pen/JqJKRW and it shows the same problem as on our page whereas we are using a slightly different configuration. Will try to simplify the example in the next few days.

**Comment by Shc0d** [comment]
Hello, the problem is still not solved.
