### ISSUE TITLE
loop is true not working

### ISSUE THREAD

**Issue by mahendrushivam** [kidjp85/react-id-swiper#183]
When using loop:true, with slidePerView auto , it results in failure

**Comment by rafaponieman** [comment]
Using slidesPerView: 1 and loop: true also fails for me. It doesn't render the Swiper at all.

**Comment by dblodorn** [comment]
@rafaponieman @mahendrushivam @kidjp85 - has anyone had luck with this? Would love to use this port - but confused as to why this functionality is not included?

**Comment by dblodorn** [comment]
Actually - Got it working - my slideshow was more complex - was referencing swiper.realIndex because I have it set so some slides are videos - and want to stop start video when arriving / leaving slide that holds a video - so when loop is set to true i get errors on the realIndex - which may be worth looking at.

    _slideChange() {
      const slideIndex = this.swiper.realIndex
      const slideType = this.swiper.slides[slideIndex].dataset.slidetype
      if (slideType === 'video' && (this.player != undefined)) {
        this._onPlay()
      } else {
        this._stop()
      }
    }

**Comment by kidjp85** [comment]
I think it should work when you fix the width for each slide. If you still face that issue please provide live demo from Codesandbox I created. The link is in README
