### ISSUE TITLE
removed css

### ISSUE THREAD

**Issue by lhtdesignde** [kidjp85/react-id-swiper#195]
In the new release 1.6.7 you removed the css. I'm wondering why?
I'm using the swiper in a react project which symlinks to the css from the package. That would have worked great with all package update except when it got removed now.

**Comment by JorgeIbarra-natgeo** [comment]
Same issue here, why was it removed?

**Comment by kidjp85** [comment]
Hi folks, the reason I removed styles folder is because it takes a lot of effort to keep up-to-date with newest stylesheet from Swiper team. I can take it back in next version, but I won't support `less` and `scss`. For temporary solution, please use stylesheet from Swiper team `https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.css`
