### ISSUE TITLE
How to use custom prev and next buttons?

### ISSUE THREAD

**Issue by rodsfreitas** [kidjp85/react-id-swiper#34]
Hi! I tried, inside prevButton and nextButton params, to put a custom class instead of swiper-button-prev and swiper-button-next and the buttons stopped working.

How is it possible to create custom prev and next buttons using your wrapper?

**Comment by JohannesFischer** [comment]
It should work fine if you pass anything like `.my-class`.

The contents of the prev and next button props will be passed to the Swiper which uses them as a selector find the buttons and attach the according events to.

As the Swiper API docs say:

> String with CSS selector or HTML element of the element that will work like "next" button after click on it

Please make sure to pass a valid selector and avoid multiple class names like `.my-class.another-class` since the passed string replaces dots with an empty string in the current version.

**Comment by kidjp85** [comment]
Hi @rodsfreitas , in newest version 1.2.1, I added new params which allow you to add your class name to prev and next button. Please check README file. Thanks
