### ISSUE TITLE
rtl props seems wrong typed

### ISSUE THREAD

**Issue by damien916** [kidjp85/react-id-swiper#361]
Hello

`rtl` props is typed as `string` but it seems it should be boolean to work with `dir={rtl && 'rtl'}`

**Comment by jgfidelis** [comment]
I think in fact it should be `dir={rtl === 'rtl'}`. The type is right, the usage of the prop that is wrong

**Comment by damien916** [comment]
No I think the html props `dir` is waiting for `rtl`, `ltr` or `auto` but not a boolean.

**Comment by kidjp85** [comment]
I think the current prop type for `rtl` is correct

**Comment by mohux** [comment]
Its not correct, even if i pass ltr, it treats it as RTL

and if i dynamically change from RTL to LTR

there is a bug that lets the swiper overflow to the left

**Comment by sajadjafari** [comment]
For far as I remember, swiper had this issue always...
For every project, I say I would never use this package and end up using it because I've no enough time to find a better one without any issue...

When you try to change the direction dynamically, it won't work, but it's fine with reload... please please please fix this issue. I'm dealing with this bug for 2 years and it's still there!!!
