### ISSUE TITLE
Problem with react-id-swiper [Chrome update 79 -> 80]  🚨

### ISSUE THREAD

**Issue by patsadow2** [kidjp85/react-id-swiper#390]
Hello, there is a problem with width of swiper-slide which add unnormouse width to swiper-slide after update chromer from version 79 to 80.

`<div class="swiper-slide swiper-slide-active" style="width: 1.11848e+07px;">`

I saw there is someone who have problem with also slider: 
https://support.google.com/chrome/thread/27904178

The problem is even in simple examples

**Comment by ixuxinyue** [comment]
I met the same problem when I changed the length of Swiper in redux.

**Comment by patsadow2** [comment]
I believe everyone will have the same problem after chrome update since it's not working on simple examples.

**Comment by ixuxinyue** [comment]
> I believe everyone will have the same problem after chrome update since it's not working on simple examples.
> 
> @ixuxinyue Do you have any workaround ?

No, I haven't yet.

**Comment by patsadow2** [comment]
it's very weird that people doesn't have that problem, do they ever heard about reponsive web ?

@ixuxinyue  Have you find out something ?

**Comment by ixuxinyue** [comment]
> it's very weird that people doesn't have that problem, do they ever heard about reponsive web ?
> 
> @ixuxinyue Have you find out something ?

This problem occurs when I drag the browser's border to reduce the width of the browser client. And even I switch to another screen, and then switched back, it sometimes happens. And I tried it in firefox and safari, it also happens. So I wonder if the reason is Chrome's update.

By the way, because I use the vertical scrolling(mouse wheel control), so instead of huge number of width shown in your problem, mine is 
`<div class="swiper-slide mobile-slide-item swiper-slide-active" style="height: 3.35544e+07px; margin-bottom: 30px;"></div>`
I also want to know why and how to resolve it QAQ
